### PR TITLE
Bump dependencies

### LINKED ISSUE #92: Bump dependencies

### PR DESCRIPTION
**Pull request by pavel-mikula-sonarsource**
Fixes #92

### CODE REVIEW

**Review by sebastien-marichal — CHANGES_REQUESTED** [review]
When I do an update locally, I have `node_modules\.bin\uuid` that is updated as well.
Why it is missing in this PR?

**Comment by pavel-mikula-sonarsource** [comment]
> When I do an update locally, I have `node_modules\.bin\uuid` that is updated as well. Why it is missing in this PR?

I don't know. `npm update` nor `npm update uuid` doesn't change that file for me

**Comment by sebastien-marichal** [comment]
I am using `npm install` after deleting the `node_modules` folder to get the update `uuid`.

Also, `npm update` updates all registry URLs from npmjs to repox in the `package-lock.json`:
```diff
  "node_modules/@actions/github": {
    "version": "5.1.1",
-   "resolved": "https://registry.npmjs.org/@actions/github/-/github-5.1.1.tgz",
+   "resolved": "https://repox.jfrog.io/artifactory/api/npm/npm/@actions/github/-/github-5.1.1.tgz",
    "integrity": "sha512-Nk59rMDoJaV+mHCOJPXuvB1zIbomlKS0dmSIqPGxd0enAXBnOfn4VWF+CGtRCwXZG9Epa54tZA7VIRlJDS8A6g==",
    "dependencies": {
      "@actions/http-client": "^2.0.1",
      "@octokit/core": "^3.6.0",
      "@octokit/plugin-paginate-rest": "^2.17.0",
      "@octokit/plugin-rest-endpoint-methods": "^5.13.0"
    }
  },
```

**Comment by pavel-mikula-sonarsource** [comment]
I've updated the uuid by deleting the `node_modules`. That sounds like a unreliable package manager 🤦

**Review by sebastien-marichal — APPROVED** [review]
LGTM!

**Pull request merged**
